//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 22-Apr-18 4:39:02 PM
namespace EventManagement_Client.ServiceReference1
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "EventManagement_Api.Models", "EventManagement_Client.ServiceReference1");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("EventManagement_Client.ServiceReference1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("EventManagement_Api.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for BookingDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<BookingDetails> BookingDetails
        {
            get
            {
                if ((this._BookingDetails == null))
                {
                    this._BookingDetails = base.CreateQuery<BookingDetails>("BookingDetails");
                }
                return this._BookingDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<BookingDetails> _BookingDetails;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<Product>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Product> _Products;
        /// <summary>
        /// There are no comments for Catagories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Catagory> Catagories
        {
            get
            {
                if ((this._Catagories == null))
                {
                    this._Catagories = base.CreateQuery<Catagory>("Catagories");
                }
                return this._Catagories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Catagory> _Catagories;
        /// <summary>
        /// There are no comments for Events in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Event> Events
        {
            get
            {
                if ((this._Events == null))
                {
                    this._Events = base.CreateQuery<Event>("Events");
                }
                return this._Events;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Event> _Events;
        /// <summary>
        /// There are no comments for BookingDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBookingDetails(BookingDetails bookingDetails)
        {
            base.AddObject("BookingDetails", bookingDetails);
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
        /// <summary>
        /// There are no comments for Catagories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCatagories(Catagory catagory)
        {
            base.AddObject("Catagories", catagory);
        }
        /// <summary>
        /// There are no comments for Events in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEvents(Event @event)
        {
            base.AddObject("Events", @event);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"EventManagement_Api.Models\" xmlns=\"http://schemas.microsoft.com/ado/2" +
                "009/11/edm\"><EntityType Name=\"BookingDetails\"><Key><PropertyRef Name=\"BookingID\"" +
                " /></Key><Property Name=\"BookingID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Propert" +
                "y Name=\"BookingDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Even" +
                "tDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"EventId\" Type=\"Edm" +
                ".Int32\" Nullable=\"false\" /><Property Name=\"GuestNo\" Type=\"Edm.Int32\" Nullable=\"f" +
                "alse\" /><Property Name=\"Catagory\" Type=\"Edm.String\" /><Property Name=\"ProductID\"" +
                " Type=\"Edm.String\" /><Property Name=\"ProductName\" Type=\"Edm.String\" /><Property " +
                "Name=\"Quantity\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"ProductCost\"" +
                " Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"Product\" Relation" +
                "ship=\"EventManagement_Api.Models.EventManagement__Api_Models_BookingDetails_Prod" +
                "uct_EventManagement__Api_Models_Product_ProductPartner\" ToRole=\"Product\" FromRol" +
                "e=\"ProductPartner\" /><NavigationProperty Name=\"Event\" Relationship=\"EventManagem" +
                "ent_Api.Models.EventManagement__Api_Models_BookingDetails_Event_EventManagement_" +
                "_Api_Models_Event_EventPartner\" ToRole=\"Event\" FromRole=\"EventPartner\" /></Entit" +
                "yType><EntityType Name=\"Product\"><Key><PropertyRef Name=\"ProductId\" /></Key><Pro" +
                "perty Name=\"ProductId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Catag" +
                "oryId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"ProductName\" Type=\"Ed" +
                "m.String\" /><Property Name=\"PictureFile\" Type=\"Edm.String\" /><Property Name=\"Pic" +
                "ture\" Type=\"Edm.String\" /><Property Name=\"ProductCost\" Type=\"Edm.Int32\" Nullable" +
                "=\"false\" /><NavigationProperty Name=\"Catagory\" Relationship=\"EventManagement_Api" +
                ".Models.EventManagement__Api_Models_Product_Catagory_EventManagement__Api_Models" +
                "_Catagory_CatagoryPartner\" ToRole=\"Catagory\" FromRole=\"CatagoryPartner\" /></Enti" +
                "tyType><EntityType Name=\"Catagory\"><Key><PropertyRef Name=\"CatagoryId\" /></Key><" +
                "Property Name=\"CatagoryId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"C" +
                "atagoryName\" Type=\"Edm.String\" /><NavigationProperty Name=\"Products\" Relationshi" +
                "p=\"EventManagement_Api.Models.EventManagement__Api_Models_Catagory_Products_Even" +
                "tManagement__Api_Models_Product_ProductsPartner\" ToRole=\"Products\" FromRole=\"Pro" +
                "ductsPartner\" /></EntityType><EntityType Name=\"Event\"><Key><PropertyRef Name=\"Ev" +
                "entId\" /></Key><Property Name=\"EventId\" Type=\"Edm.Int32\" Nullable=\"false\" /><Pro" +
                "perty Name=\"EventName\" Type=\"Edm.String\" /></EntityType><Association Name=\"Event" +
                "Management__Api_Models_BookingDetails_Product_EventManagement__Api_Models_Produc" +
                "t_ProductPartner\"><End Type=\"EventManagement_Api.Models.Product\" Role=\"Product\" " +
                "Multiplicity=\"*\" /><End Type=\"EventManagement_Api.Models.BookingDetails\" Role=\"P" +
                "roductPartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"EventManag" +
                "ement__Api_Models_BookingDetails_Event_EventManagement__Api_Models_Event_EventPa" +
                "rtner\"><End Type=\"EventManagement_Api.Models.Event\" Role=\"Event\" Multiplicity=\"*" +
                "\" /><End Type=\"EventManagement_Api.Models.BookingDetails\" Role=\"EventPartner\" Mu" +
                "ltiplicity=\"0..1\" /></Association><Association Name=\"EventManagement__Api_Models" +
                "_Product_Catagory_EventManagement__Api_Models_Catagory_CatagoryPartner\"><End Typ" +
                "e=\"EventManagement_Api.Models.Catagory\" Role=\"Catagory\" Multiplicity=\"0..1\" /><E" +
                "nd Type=\"EventManagement_Api.Models.Product\" Role=\"CatagoryPartner\" Multiplicity" +
                "=\"0..1\" /><ReferentialConstraint><Principal Role=\"Catagory\"><PropertyRef Name=\"C" +
                "atagoryId\" /></Principal><Dependent Role=\"CatagoryPartner\"><PropertyRef Name=\"Ca" +
                "tagoryId\" /></Dependent></ReferentialConstraint></Association><Association Name=" +
                "\"EventManagement__Api_Models_Catagory_Products_EventManagement__Api_Models_Produ" +
                "ct_ProductsPartner\"><End Type=\"EventManagement_Api.Models.Product\" Role=\"Product" +
                "s\" Multiplicity=\"*\" /><End Type=\"EventManagement_Api.Models.Catagory\" Role=\"Prod" +
                "uctsPartner\" Multiplicity=\"0..1\" /></Association></Schema><Schema Namespace=\"Def" +
                "ault\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name" +
                "=\"Container\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"BookingDetails\" " +
                "EntityType=\"EventManagement_Api.Models.BookingDetails\" /><EntitySet Name=\"Produc" +
                "ts\" EntityType=\"EventManagement_Api.Models.Product\" /><EntitySet Name=\"Catagorie" +
                "s\" EntityType=\"EventManagement_Api.Models.Catagory\" /><EntitySet Name=\"Events\" E" +
                "ntityType=\"EventManagement_Api.Models.Event\" /><AssociationSet Name=\"EventManage" +
                "ment__Api_Models_BookingDetails_Product_EventManagement__Api_Models_Product_Prod" +
                "uctPartnerSet\" Association=\"EventManagement_Api.Models.EventManagement__Api_Mode" +
                "ls_BookingDetails_Product_EventManagement__Api_Models_Product_ProductPartner\"><E" +
                "nd Role=\"ProductPartner\" EntitySet=\"BookingDetails\" /><End Role=\"Product\" Entity" +
                "Set=\"Products\" /></AssociationSet><AssociationSet Name=\"EventManagement__Api_Mod" +
                "els_BookingDetails_Event_EventManagement__Api_Models_Event_EventPartnerSet\" Asso" +
                "ciation=\"EventManagement_Api.Models.EventManagement__Api_Models_BookingDetails_E" +
                "vent_EventManagement__Api_Models_Event_EventPartner\"><End Role=\"EventPartner\" En" +
                "titySet=\"BookingDetails\" /><End Role=\"Event\" EntitySet=\"Events\" /></AssociationS" +
                "et><AssociationSet Name=\"EventManagement__Api_Models_Product_Catagory_EventManag" +
                "ement__Api_Models_Catagory_CatagoryPartnerSet\" Association=\"EventManagement_Api." +
                "Models.EventManagement__Api_Models_Product_Catagory_EventManagement__Api_Models_" +
                "Catagory_CatagoryPartner\"><End Role=\"CatagoryPartner\" EntitySet=\"Products\" /><En" +
                "d Role=\"Catagory\" EntitySet=\"Catagories\" /></AssociationSet><AssociationSet Name" +
                "=\"EventManagement__Api_Models_Catagory_Products_EventManagement__Api_Models_Prod" +
                "uct_ProductsPartnerSet\" Association=\"EventManagement_Api.Models.EventManagement_" +
                "_Api_Models_Catagory_Products_EventManagement__Api_Models_Product_ProductsPartne" +
                "r\"><End Role=\"ProductsPartner\" EntitySet=\"Catagories\" /><End Role=\"Products\" Ent" +
                "itySet=\"Products\" /></AssociationSet></EntityContainer></Schema></edmx:DataServi" +
                "ces></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for EventManagement_Api.Models.BookingDetails in the schema.
    /// </summary>
    /// <KeyProperties>
    /// BookingID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("BookingID")]
    public partial class BookingDetails
    {
        /// <summary>
        /// Create a new BookingDetails object.
        /// </summary>
        /// <param name="bookingID">Initial value of BookingID.</param>
        /// <param name="bookingDate">Initial value of BookingDate.</param>
        /// <param name="eventDate">Initial value of EventDate.</param>
        /// <param name="eventId">Initial value of EventId.</param>
        /// <param name="guestNo">Initial value of GuestNo.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        /// <param name="productCost">Initial value of ProductCost.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static BookingDetails CreateBookingDetails(int bookingID, global::System.DateTime bookingDate, global::System.DateTime eventDate, int eventId, int guestNo, int quantity, int productCost)
        {
            BookingDetails bookingDetails = new BookingDetails();
            bookingDetails.BookingID = bookingID;
            bookingDetails.BookingDate = bookingDate;
            bookingDetails.EventDate = eventDate;
            bookingDetails.EventId = eventId;
            bookingDetails.GuestNo = guestNo;
            bookingDetails.Quantity = quantity;
            bookingDetails.ProductCost = productCost;
            return bookingDetails;
        }
        /// <summary>
        /// There are no comments for Property BookingID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int BookingID
        {
            get
            {
                return this._BookingID;
            }
            set
            {
                this.OnBookingIDChanging(value);
                this._BookingID = value;
                this.OnBookingIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _BookingID;
        partial void OnBookingIDChanging(int value);
        partial void OnBookingIDChanged();
        /// <summary>
        /// There are no comments for Property BookingDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime BookingDate
        {
            get
            {
                return this._BookingDate;
            }
            set
            {
                this.OnBookingDateChanging(value);
                this._BookingDate = value;
                this.OnBookingDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _BookingDate;
        partial void OnBookingDateChanging(global::System.DateTime value);
        partial void OnBookingDateChanged();
        /// <summary>
        /// There are no comments for Property EventDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime EventDate
        {
            get
            {
                return this._EventDate;
            }
            set
            {
                this.OnEventDateChanging(value);
                this._EventDate = value;
                this.OnEventDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _EventDate;
        partial void OnEventDateChanging(global::System.DateTime value);
        partial void OnEventDateChanged();
        /// <summary>
        /// There are no comments for Property EventId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EventId
        {
            get
            {
                return this._EventId;
            }
            set
            {
                this.OnEventIdChanging(value);
                this._EventId = value;
                this.OnEventIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EventId;
        partial void OnEventIdChanging(int value);
        partial void OnEventIdChanged();
        /// <summary>
        /// There are no comments for Property GuestNo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int GuestNo
        {
            get
            {
                return this._GuestNo;
            }
            set
            {
                this.OnGuestNoChanging(value);
                this._GuestNo = value;
                this.OnGuestNoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _GuestNo;
        partial void OnGuestNoChanging(int value);
        partial void OnGuestNoChanged();
        /// <summary>
        /// There are no comments for Property Catagory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Catagory
        {
            get
            {
                return this._Catagory;
            }
            set
            {
                this.OnCatagoryChanging(value);
                this._Catagory = value;
                this.OnCatagoryChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Catagory;
        partial void OnCatagoryChanging(string value);
        partial void OnCatagoryChanged();
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductID;
        partial void OnProductIDChanging(string value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this._ProductName = value;
                this.OnProductNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property ProductCost in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductCost
        {
            get
            {
                return this._ProductCost;
            }
            set
            {
                this.OnProductCostChanging(value);
                this._ProductCost = value;
                this.OnProductCostChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductCost;
        partial void OnProductCostChanging(int value);
        partial void OnProductCostChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Product> Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                if ((value != null))
                {
                    this._Product = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Product> _Product = new global::System.Collections.ObjectModel.Collection<Product>();
        /// <summary>
        /// There are no comments for Event in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Event> Event
        {
            get
            {
                return this._Event;
            }
            set
            {
                if ((value != null))
                {
                    this._Event = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Event> _Event = new global::System.Collections.ObjectModel.Collection<Event>();
    }
    /// <summary>
    /// There are no comments for EventManagement_Api.Models.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProductId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProductId")]
    public partial class Product
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="productId">Initial value of ProductId.</param>
        /// <param name="catagoryId">Initial value of CatagoryId.</param>
        /// <param name="productCost">Initial value of ProductCost.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Product CreateProduct(int productId, int catagoryId, int productCost)
        {
            Product product = new Product();
            product.ProductId = productId;
            product.CatagoryId = catagoryId;
            product.ProductCost = productCost;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ProductId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductId
        {
            get
            {
                return this._ProductId;
            }
            set
            {
                this.OnProductIdChanging(value);
                this._ProductId = value;
                this.OnProductIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductId;
        partial void OnProductIdChanging(int value);
        partial void OnProductIdChanged();
        /// <summary>
        /// There are no comments for Property CatagoryId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CatagoryId
        {
            get
            {
                return this._CatagoryId;
            }
            set
            {
                this.OnCatagoryIdChanging(value);
                this._CatagoryId = value;
                this.OnCatagoryIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CatagoryId;
        partial void OnCatagoryIdChanging(int value);
        partial void OnCatagoryIdChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this._ProductName = value;
                this.OnProductNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property PictureFile in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PictureFile
        {
            get
            {
                return this._PictureFile;
            }
            set
            {
                this.OnPictureFileChanging(value);
                this._PictureFile = value;
                this.OnPictureFileChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PictureFile;
        partial void OnPictureFileChanging(string value);
        partial void OnPictureFileChanged();
        /// <summary>
        /// There are no comments for Property Picture in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Picture
        {
            get
            {
                return this._Picture;
            }
            set
            {
                this.OnPictureChanging(value);
                this._Picture = value;
                this.OnPictureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Picture;
        partial void OnPictureChanging(string value);
        partial void OnPictureChanged();
        /// <summary>
        /// There are no comments for Property ProductCost in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProductCost
        {
            get
            {
                return this._ProductCost;
            }
            set
            {
                this.OnProductCostChanging(value);
                this._ProductCost = value;
                this.OnProductCostChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProductCost;
        partial void OnProductCostChanging(int value);
        partial void OnProductCostChanged();
        /// <summary>
        /// There are no comments for Catagory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Catagory Catagory
        {
            get
            {
                return this._Catagory;
            }
            set
            {
                this._Catagory = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Catagory _Catagory;
    }
    /// <summary>
    /// There are no comments for EventManagement_Api.Models.Catagory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CatagoryId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CatagoryId")]
    public partial class Catagory
    {
        /// <summary>
        /// Create a new Catagory object.
        /// </summary>
        /// <param name="catagoryId">Initial value of CatagoryId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Catagory CreateCatagory(int catagoryId)
        {
            Catagory catagory = new Catagory();
            catagory.CatagoryId = catagoryId;
            return catagory;
        }
        /// <summary>
        /// There are no comments for Property CatagoryId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CatagoryId
        {
            get
            {
                return this._CatagoryId;
            }
            set
            {
                this.OnCatagoryIdChanging(value);
                this._CatagoryId = value;
                this.OnCatagoryIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CatagoryId;
        partial void OnCatagoryIdChanging(int value);
        partial void OnCatagoryIdChanged();
        /// <summary>
        /// There are no comments for Property CatagoryName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CatagoryName
        {
            get
            {
                return this._CatagoryName;
            }
            set
            {
                this.OnCatagoryNameChanging(value);
                this._CatagoryName = value;
                this.OnCatagoryNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CatagoryName;
        partial void OnCatagoryNameChanging(string value);
        partial void OnCatagoryNameChanged();
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Product> Products
        {
            get
            {
                return this._Products;
            }
            set
            {
                if ((value != null))
                {
                    this._Products = value;
                }
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Product> _Products = new global::System.Collections.ObjectModel.Collection<Product>();
    }
    /// <summary>
    /// There are no comments for EventManagement_Api.Models.Event in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EventId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EventId")]
    public partial class Event
    {
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="eventId">Initial value of EventId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Event CreateEvent(int eventId)
        {
            Event @event = new Event();
            @event.EventId = eventId;
            return @event;
        }
        /// <summary>
        /// There are no comments for Property EventId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EventId
        {
            get
            {
                return this._EventId;
            }
            set
            {
                this.OnEventIdChanging(value);
                this._EventId = value;
                this.OnEventIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EventId;
        partial void OnEventIdChanging(int value);
        partial void OnEventIdChanged();
        /// <summary>
        /// There are no comments for Property EventName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EventName
        {
            get
            {
                return this._EventName;
            }
            set
            {
                this.OnEventNameChanging(value);
                this._EventName = value;
                this.OnEventNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EventName;
        partial void OnEventNameChanging(string value);
        partial void OnEventNameChanged();
    }
}
